from dotenv import load_dotenv                                                                                                                                                                                                                        
from langchain_openai import ChatOpenAI                                                                                                                                                                                                               
from deepagents import create_deep_agent                                                                                                                                                                                                              
                                                                                                                                                                                                                                                    
load_dotenv()                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                    
model = ChatOpenAI(model="gpt-4o-mini", temperature=0)                                                                                                                                                                                                
                                                                                                                                                                                                                                                    
# DEFAULT: StateBackend (no backend parameter)                                                                                                                                                                                                        
# Files stored in agent state (memory), lost when session ends                                                                                                                                                                                        
agent = create_deep_agent(model=model)                                                                                                                                                                                                                
                                                                                                                                                                                                                                                    
# Ask agent to write a file                                                                                                                                                                                                                           
response = agent.invoke({                                                                                                                                                                                                                             
    "messages": [{"role": "user", "content":                                                                                                                                                                                                          
        "Write a file called /notes.txt with the text 'Hello from StateBackend'. "                                                                                                                                                                    
        "Then read it back and tell me what it says."                                                                                                                                                                                                 
    }]                                                                                                                                                                                                                                                
})                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                    
print("=== RESPONSE ===")                                                                                                                                                                                                                             
print(response["messages"][-1].content) 